site_name: XDAO TON Documentation
site_description: DAO in Telegram. Powered by TON.
site_url: https://davidosick.github.io/xdao-books/


# Configuration
theme:
  name: material
  language: en
  logo: assets/images/xdao.svg
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.footer
    - navigation.indexes
    - toc.follow
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy

# Plugins
plugins:
  - search:
      lang: en
  - minify:
      minify_html: true

# Extensions
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji

# Page tree
nav:
  - Home: README.md
  - Architecture:
    - Glossary: architecture/glossary.md
    - General Concept: architecture/general-concept.md
    - Telegram Mini App: architecture/telegram-mini-app.md
    - TON Smart Contracts: architecture/ton-smart-contracts.md
    - TON Wallet Integrations: architecture/ton-wallet-integrations.md
  - Guides:
    - Launching the Bot: guides-for-gt/launching-the-bot.md
    - Connecting Wallet: guides-for-gt/connecting-wallet.md
    - Create a DAO: guides-for-gt/create-a-dao.md
    - DAO Information: guides-for-gt/dao-information.md
    - Proposals: guides-for-gt/proposals.md
  - Basics:
    - FAQ: basics/interactive-blocks.md
    - Contact us: basics/integrations.md

# Extra
extra:
  social:
    - icon: fontawesome/brands/telegram
      link: https://t.me/xdao_app
    - icon: fontawesome/solid/globe
      link: https://xdao.app/

# Copyright
copyright: Copyright &copy; 2025 XDAO
